import './globals.css'
 
import LeftSidebar from "@/components/shared/LeftSidebar";
import Bottombar from "@/components/shared/Bottombar";
import RightSidebar from "@/components/shared/RightSidebar";
import Topbar from "@/components/shared/Topbar";

export const metadata = {
  title: 'Learning & Assessment Platform',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
    <body> 
      <Topbar/>

      <main className='flex flex-row '>
        <LeftSidebar />
        <section className='main-container w-full'>
          <div className='w-full max-w-2xl'>{children}</div>
        </section>
        
        <RightSidebar />
      </main>

      <Bottombar />
    </body>
  </html>
  )
}




// import React from "react";
// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import { ClerkProvider } from "@clerk/nextjs";
// import { dark } from "@clerk/themes";

// import "../globals.css";
// import LeftSidebar from "@/components/shared/LeftSidebar";
// import Bottombar from "@/components/shared/Bottombar";
// import RightSidebar from "@/components/shared/RightSidebar";
// import Topbar from "@/components/shared/Topbar";

 

// export const metadata: Metadata = {
//   title: "Threads",
//   description: "A Next.js 13 Meta Threads application",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <ClerkProvider
//       appearance={{
//         baseTheme: dark,
//       }}
//     >
//       <html lang='en'>
//         <body> 
//           <Topbar/>

//           <main className='flex flex-row '>
//             <LeftSidebar />
//             <section className='main-container w-full'>
//               <div className='w-full max-w-2xl'>{children}</div>
//             </section>
            
//             <RightSidebar />
//           </main>

//           <Bottombar />
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
